// <auto-generated />
namespace Regele_Marius.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingValidators : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingValidators));
        
        string IMigrationMetadata.Id
        {
            get { return "202104141155332_AddingValidators"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
